function naviMsg = naviMsgInitializing(naviMsg, systConfig)

BDS_maxPrnNo = systConfig.BDS_B1I.maxPrnNo;
GPS_maxPrnNo = systConfig.GPS_L1CA.maxPrnNo; %L2C与L1CA相同

% 历书子结构体 -- B1I & L1CA
alm = struct( ...  almanac struct
    'deltai',                'N', ...
    'M0' ,                   'N', ...
    'e',                     'N', ...
    'sqrtA',                 'N', ...
    'omegaDot',              'N', ...
    'omega0',                'N', ...
    'omega',                 'N', ...   
    'toa',                   'N', ...
    'a1',                    'N', ...
    'a0',                    'N' ...
);

%% BDS_B1I 历书结构体
naviMsg.BDS_B1I.almanac.syst = 'BDS_B1I';
naviMsg.BDS_B1I.almanac.almAllReady = 0;
naviMsg.BDS_B1I.almanac.dect = zeros(1, BDS_maxPrnNo);
naviMsg.BDS_B1I.almanac.hea    = -1 * ones(1, BDS_maxPrnNo);
naviMsg.BDS_B1I.almanac.WNa    = 0;
naviMsg.BDS_B1I.almanac.alm = repmat(alm,1,BDS_maxPrnNo);

%% BDS_B1I 星历结构体
ephStr_BDS = struct(...  Ephemeris struct
    'deltan',                'N', ...
    'Cuc',                   'N', ...
    'M0' ,                   'N', ...
    'e',                     'N', ...
    'Cus',                   'N', ...
    'Crc',                   'N', ...
    'Crs',                   'N', ...
    'sqrtA',                 'N', ...
    'i0',                    'N', ...
    'Cic',                   'N', ...
    'omegaDot',              'N', ...
    'Cis',                   'N', ...
    'iDot',                  'N', ...
    'omega0',                'N', ...
    'omega',                 'N', ...
    'weekNumber',            'N', ...
    'health',                'N', ...
    'TGD1',                  'N', ...
    'IODC',                  'N', ...
    'toc',                   'N', ...
    'a2',                    'N', ...
    'a1',                    'N', ...
    'a0',                    'N', ...
    'Alpha0',                'N', ...
    'Alpha1',                'N', ...
    'Alpha2',                'N', ...
    'Alpha3',                'N', ...
    'Beta0',                 'N', ...
    'Beta1',                 'N', ...
    'Beta2',                 'N', ...
    'Beta3',                 'N', ...
    'IODE',                  'N', ...
    'A0utc',                 'N', ...
    'A1utc',                 'N', ...
    'deltaTls',              'N', ...
    'deltaTlsf',             'N', ...
    'WNlsf',                 'N', ...
    'DN',                    'N', ...
    'A0gps',                 'N', ...
    'A1gps',                 'N', ...
    'toe',                   'N' ...
);

rawEph_GEO = struct(...
    'a1h',                   [], ...
    'a1m',                   [], ...
    'a1l',                   [], ...
    'Cuch',                  [], ...
    'Cucl',                  [], ...
    'eh',                    [], ...
    'em',                    [], ...
    'el',                    [], ...
    'Cich',                  [], ...
    'Cicm',                  [], ...
    'Cicl',                  [], ...
    'i0h',                   [], ...
    'i0m1',                  [], ...
    'i0m2',                  [], ...
    'i0l',                   [], ...
    'omegah',                [], ...
    'omegam',                [], ...
    'omegal',                [], ...
    'omegaDoth',             [], ...
    'omegaDotm',             [], ...
    'omegaDotl',             []  ...
);

rawEph_NGEO = struct(...
    'toel',                  [], ...
    'toeh',                  []  ...
);

ephemerisValue_BDS = struct( ...
    'ephReady',             0,                        ...       % Whether ephemeris data is ready to use in pvt calculation, 0 means not yet
    'subframeID',           [1 2 3 4 5 6 7 8 9 10],   ...       % 5 subframes in one frame
    'ephUpdate',            ephStr_BDS,               ...       % Ephemeris struct, saving latest navigation messages which is not validated.
    'ephRaid',              ephStr_BDS,               ...
    'updateReady',          0,                        ...       % Whether ephemeris data update completely
    'updating',             0,                        ...       % The value equals to 1, while eph is updating
    'eph',                  ephStr_BDS,               ...       % eph we used
    'ephTrustLevel',        0,                        ...       % how trustable is the eph which we are using:
                                                      ...         0 - unchecked; 
                                                      ...         1 - pass the preliminary eph extent check;
                                                      ...         2 - pass the sat2earth-center range check;
                                                      ...         3 - pass the historical eph pseudorange comparison check; 
                                                      ...         4 - pass the RAIM check, the current eph can be trustably used.
    'ephUpdateTrustLevel',  0,                        ...
    'rawEph',               [] ...
);

ephemerisValue_BDS(1:BDS_maxPrnNo) = ephemerisValue_BDS;
for i=1:5
    ephemerisValue_BDS(i).rawEph = rawEph_GEO;
end
for i=6:BDS_maxPrnNo
    ephemerisValue_BDS(i).rawEph = rawEph_NGEO;
end

naviMsg.BDS_B1I.ephemeris = ephemerisValue_BDS;

%% GPS_L1CA 历书结构体
naviMsg.GPS_L1CA.almanac.syst = 'GPS_L1CA';
naviMsg.GPS_L1CA.almanac.almAllReady = 0;
naviMsg.GPS_L1CA.almanac.dect   = zeros(1, GPS_maxPrnNo);
naviMsg.GPS_L1CA.almanac.hea    = -1 * ones(1, GPS_maxPrnNo);
naviMsg.GPS_L1CA.almanac.WNa    = 0;
naviMsg.GPS_L1CA.almanac.alm = repmat(alm,1,GPS_maxPrnNo);

%% GPS_L1CA 星历结构体
ephStr_GPS = struct(... Ephemeris struct
    'deltan',                'N', ...
    'Cuc',                   'N', ...
    'M0' ,                   'N', ...
    'e',                     'N', ...
    'Cus',                   'N', ...
    'Crc',                   'N', ...
    'Crs',                   'N', ...
    'sqrtA',                 'N', ...
    'i0',                    'N', ...
    'Cic',                   'N', ...
    'omegaDot',              'N', ...
    'Cis',                   'N', ...
    'iDot',                  'N', ...
    'omega0',                'N', ...
    'omega',                 'N', ...
    'weekNumber',            'N', ...
    'health',                'N', ...
    'TGD',                   'N', ...
    'IODC',                  'N', ...
    'toc',                   'N', ...
    'af2',                   'N', ...
    'af1',                   'N', ...
    'af0',                   'N', ...
    'Alpha0',                'N', ...
    'Alpha1',                'N', ...
    'Alpha2',                'N', ...
    'Alpha3',                'N', ...
    'Beta0',                 'N', ...
    'Beta1',                 'N', ...
    'Beta2',                 'N', ...
    'Beta3',                 'N', ...
    'IODE',                  'N', ...
    'IODE2',                 'N', ...
    'toe',                   'N', ...
    'A0utc',                 'N', ...
    'A1utc',                 'N', ...
    'deltaTls',              'N', ...
    'deltaTlsf',             'N', ...
    'WNt',                   'N', ...
    'WNlsf',                 'N', ...
    'DN',                    'N', ...
    'tot',                   'N'  ...
);

ephemerisValue_GPS = struct( ...
    'ephReady',             0,                        ...       % Whether ephemeris data is ready to use in pvt calculation, 0 means not yet
    'subframeID',           [1 2 3 4 5 6 7 8 9 10],   ...       % 5 subframes in one frame
    'ephUpdate',            ephStr_GPS,               ...       % Ephemeris struct, saving latest navigation messages which is not validated.
    'ephRaid',              ephStr_GPS,               ...
    'updateReady',          0,                        ...       % Whether ephemeris data update completely
    'updating',             0,                        ...       % The value equals to 1, while eph is updating
    'eph',                  ephStr_GPS,               ...       % eph we used
    'ephTrustLevel',        0,                        ...       % how trustable is the eph which we are using: 
                                                      ...         0 - unchecked; 
                                                      ...         1 - pass the preliminary eph extent check;
                                                      ...         2 - pass the sat2earth-center range check;
                                                      ...         3 - pass the historical eph pseudorange comparison check; 
                                                      ...         4 - pass the RAIM check, the current eph can be trustably used.
    'ephUpdateTrustLevel',  0                         ...
);

naviMsg.GPS_L1CA.ephemeris = repmat(ephemerisValue_GPS,1,GPS_maxPrnNo);

%% GPS_L2C 综合结构体
%% L2C 底层结构体定义
str_ephemeris_L2C = struct(...
    ... message 10
    'WN',               0, ...
    'L1_health',        0, ...
    'L2_health',        0, ...
    'L5_health',        0, ...
    't_op',             0, ...
    'URA_ED',           0, ...
    't_oe_10',          0, ...
    'Delta_A',          0, ...
    'A_dot',            0, ...
    'Delta_n0',         0, ...
    'Delta_n0_dot',     0, ...
    'M_0n',             0, ...
    'e_n',              0, ...
    'omega_n',          0, ...
    'integrityFlag',    0, ...
    'L2C_phasing',      0, ...
    ... message 11
    't_oe_11',          0, ...
    'Omega_0n',         0, ...
    'i_0n',             0, ...
    'Delta_Omega_dot',  0, ...
    'i_0n_dot',         0, ...
    'Cis_n',            0, ...
    'Cic_n',            0, ...
    'Crs_n',            0, ...
    'Crc_n',            0, ...
    'Cus_n',            0, ...
    'Cuc_n',            0, ...
    ... clock para
    't_oc',          0, ...
    'URA_NED0',      0, ...
    'URA_NED1',      0, ...
    'URA_NED2',      0, ...   
    'a_f0n',         0, ...
    'a_f1n',         0, ...
    'a_f2n',         0 ...
);

% group delay & inter-signal correction
str_ISC_L2C = struct(...
    'ISC_ready',    0, ...
    'T_GD',         0, ...
    'ISC_L1CA',     0, ...
    'ISC_L2C',      0, ...
    'ISC_L5I5',     0, ...
    'ISC_L5Q5',     0 ...
);

% 电离层模型参数
str_IONO_L2C = struct(...
    'IONO_ready',   0, ...
    'alpha0',       0, ...
    'alpha1',       0, ...
    'alpha2',       0, ...
    'alpha3',       0, ...
    'beta0',        0, ...
    'beta1',        0, ...
    'beta2',        0, ...
    'beta3',        0, ...
    'WN_OP',        0 ... data predict week number?
);

% 精简历书 - 待完善
str_reducedAlmanac_L2C = struct(...
    'WN_an',        0, ...
    't_oa',         0 ...
);

% 中等历书 - 待完善
str_midiAlmanac_L2C = struct(...
    'WN_an',        0, ...
    't_oa',         0 ...
);

% 地球转向参数 earth orientation parameters 
str_EOP_L2C = struct(...
    'EOP_ready',        0, ...
    't_EOP',            0, ...
    'PM_X',             0, ...
    'PM_X_dot',         0, ...
    'PM_Y',             0, ...
    'PM_Y_dot',         0, ...
    'Delta_UT1',        0, ...
    'Delta_UT1_dot',    0 ...
);

% coordinated universal time (UTC)
str_UTC_L2C = struct(...
    'UTC_ready',    0, ...
    'A_0n',         0, ...
    'A_1n',         0, ...
    'A_2n',         0, ...
    'Delta_t_LS',   0, ...
    't_ot',         0, ...
    'WN_ot',        0, ...
    'WN_LSF',       0, ...
    'DN',           0, ...
    'Delta_t_LSF',  0 ...
);

% 差分信息，待完善
str_diffCorrection_L2C = [];

% GPS/GNSS time offset parameter content
str_GGTO_L2C = struct(...
    'GGTO_ready',   0, ...
    't_GGTO',       0, ...
    'WN_GGTO',      0, ...
    'A_0GGTO',      0, ...
    'A_1GGTO',      0, ...
    'A_2GGTO',      0, ...
    'GNSS_ID',      0 ...
);

% 未使用
str_text_L2C = [];

%% L2C 中间层结构体
%由于星历和时钟参数的重要性，需要进行一次校验才能更新
str_ephemeris_ch = struct( ...
    'ephReady',            0, ... 0:此前无星历   1:至少收到一次完整星历
    'updating',            0, ... 发现新电文与原先不同，则进入更新状态
    'updateLevel',         0, ... 表示初次接收或者星历更新时的数据块接收状态,用3位二进制数表示， 
                              ... 从高到低分别表示时钟、星历1、星历2的接收状态
                              ... 例如5（101）表示已接收时钟和星历2，而未接收星历1.
    'ephUpdate',           str_ephemeris_L2C, ... 最新接收的星历
    'ephRaid',             str_ephemeris_L2C, ... 若最新星历与原先保存的不同，先暂存此处，接收第三套星历比较确认后更新
    'eph',                 str_ephemeris_L2C ...  定位所用的星历
);
  
str_ephemeris_multi = repmat(str_ephemeris_ch, 1, GPS_maxPrnNo);
str_ISC_multi = repmat(str_ISC_L2C, 1, GPS_maxPrnNo);
str_IONO_multi = repmat(str_IONO_L2C, 1, GPS_maxPrnNo);

%% 顶层
naviMsg.GPS_L2C = struct(...
    'ephemeris',        str_ephemeris_multi, ...
    'ISC',              str_ISC_multi, ...
    'IONO',             str_IONO_multi, ...
    'reducedAlmanac',   str_reducedAlmanac_L2C, ...
    'midiAlmanac',      str_midiAlmanac_L2C, ...
    'EOP',              str_EOP_L2C, ...
    'UTC',              str_UTC_L2C, ...
    'diffCorrection',   str_diffCorrection_L2C, ...
    'GGTO',             str_GGTO_L2C, ...
    'text',             str_text_L2C ...
);  

