%% This file is used to control the writing_file.
function [receiver] = RecorderInitializing(receiver)
global GSAR_CONSTANTS;
% % ----------------  Initialize receiver's record(channels) struct --------------%

filename = GSAR_CONSTANTS.STR_RECV.datafilename{1};
recordname1 = regexp(filename, '\.', 'split'); %按.分隔，去后缀名
recordname2 = regexp(recordname1(1), '\\', 'split'); %按\分隔，得到底层目录的文件名
record = recordname2{1,1}(end);
record = record{1,1};
receiver.pvtCalculator.logOutput.logName = record;


% ----------------  Initialize receiver's recvRecor struct --------------%
receiver.recvRecor.recvStatuslogName = strcat(receiver.config.logConfig.logFilePath, receiver.pvtCalculator.logOutput.logName, 'STATUS.txt');
fid_0 = fopen(receiver.recvRecor.recvStatuslogName,'w+');
fclose(fid_0);

%% Debug file control structure definition
STR_FILE_CTRL(receiver.config.recvConfig.numberOfChannels(1).channelNumAll,1) = struct(...
    'DEBUG_LEVEL',            [], ...
    'PRN_ID',                 [], ...
    'info',                   [], ...
    'isCorrShapeStore',       0, ...
    ... DEBUG_LEVEL==1
    'trk_L1L2_package',       [], ... 打包格式 具体格式与debug Level有关 -- 目前用于双频Log
    'trk_carphs',             [], ...
    'trk_carfreq',            [], ...
    ... % record the time axis of each recording variable in order to accommodate different coherent tracking time
    'trk_timeaxis',           [], ... 
    ... DEBUG_LEVEL==2
    'trk_cad_codphs_diff',    [], ...
    'trk_cad_codphs_diff_2',  [], ...
    'trk_cad_ai',             [], ...
    'trk_cad_aq',             [], ...
    'unit_active_mt',         [], ...
    'unit_active_mt_2',       [], ...
    ... % recording each active unit's CNR, monitored normalized amplitudes and its corresponding time axis
    'CNR_AmpMoni_time',       [], ...
    'cad_trch_ai',            [], ...
    'cad_trch_aq',            [], ...
    'cad_trch_a_avg',         [], ...
    'cad_trch_snr',           [], ...
    'cad_trch_active',        [], ...
    'cad_trch_cnr',           [], ...
    'cad_trch_corrM_IQ',      [], ...
    'corrM_IQ',               [],...
    'uncancelled_corrM_IQ',   [],...
    ... DEBUG_LEVEL==3
    'trk_codphs',             [], ...
    'trk_codfreq',            [], ...
    'Dch_T_IQ',               [], ...
    'cad_trch_codphs',        [], ...
    'cad_trch_codfreq',       [], ...
    'cad_trch_codphs_diff',   [], ...
    'cad_trch_a_std',         [], ...
    'cad_trch_DchT_IQ',       [], ...
    'kalman_filter_results',  [], ...
    ... DEBUG_LEVEL==4
    'Dch_Tslot_IQ',           [], ...
    ... DEBUG_LEVEL==5
    'BBSig_I',                [], ... %Downconverted baseband signal with code still in there
    'BBSig_Q',                [], ...  
    'LO_Dch_Codes',           [], ... %Locally generated data channel codes
    'LO_Pch_Codes',           [] ...  %Locally generated pilot channel codes
);

% Because the number of channels isn't equal to visible satellites' number

svNum_BDS = length(receiver.config.recvConfig.targetSatellites(1).prnNum);
svNum_GPS = length(receiver.config.recvConfig.targetSatellites(2).prnNum); 
channelNum_BDS = receiver.config.recvConfig.numberOfChannels(1).channelNum;
channelNum_GPS = receiver.config.recvConfig.numberOfChannels(2).channelNum;


for sv = 1 : svNum_BDS
    if sv <= channelNum_BDS
        prn = receiver.channels(sv).CH_B1I.PRNID;
        STR_FILE_CTRL = recorderFileIni(STR_FILE_CTRL, receiver, prn, sv, record);
    end %EOF "if sv <= channelNum"
end%EOF "for sv=1:receiver.recv_cfg.numberOfChannels"

% ----------------------------GPS -----------------------
for sv = channelNum_BDS+1 : channelNum_BDS+svNum_GPS
    if sv <= channelNum_BDS+channelNum_GPS       
        switch receiver.channels(sv).SYST
            case 'GPS_L1CA'
                prn = receiver.channels(sv).CH_L1CA.PRNID;                
            case 'GPS_L1CA_L2C'
                prn = receiver.channels(sv).CH_L1CA_L2C.PRNID;
            otherwise
                disp('Undefined channel system type!');
        end
        STR_FILE_CTRL = recorderFileIni(STR_FILE_CTRL, receiver, prn, sv, record);        
    end %EOF "if sv <= channelNum"
end%EOF "for sv=1:receiver.recv_cfg.numberOfChannels"


receiver.recorder = STR_FILE_CTRL;
end
