function isEqual = CNAV_eph_compare(eph1, eph2)

isEqual = ...
        (eph1.WN              == eph2.WN) && ...
        (eph1.L1_health       == eph2.L1_health) && ...
        (eph1.L2_health       == eph2.L2_health) && ...
        (eph1.L5_health       == eph2.L5_health) && ...
        (eph1.t_op            == eph2.t_op) && ...
        (eph1.t_oe_10         == eph2.t_oe_10) && ...
        (eph1.Delta_A         == eph2.Delta_A) && ...
        (eph1.A_dot           == eph2.A_dot) && ...
        (eph1.Delta_n0        == eph2.Delta_n0) && ...
        (eph1.Delta_n0_dot    == eph2.Delta_n0_dot) && ...
        (eph1.M_0n            == eph2.M_0n) && ...
        (eph1.e_n             == eph2.e_n) && ...
        (eph1.omega_n         == eph2.omega_n) && ...
        (eph1.integrityFlag   == eph2.integrityFlag) && ...
        (eph1.L2C_phasing     == eph2.L2C_phasing) && ...
        (eph1.URA_ED          == eph2.URA_ED) && ...
        (eph1.t_oe_11         == eph2.t_oe_11) && ...
        (eph1.Omega_0n        == eph2.Omega_0n) && ...
        (eph1.i_0n            == eph2.i_0n) && ...
        (eph1.Delta_Omega_dot == eph2.Delta_Omega_dot) && ...
        (eph1.i_0n_dot        == eph2.i_0n_dot) && ...
        (eph1.Cis_n           == eph2.Cis_n) && ...
        (eph1.Cic_n           == eph2.Cic_n) && ...
        (eph1.Crs_n           == eph2.Crs_n) && ...
        (eph1.Crc_n           == eph2.Crc_n) && ...
        (eph1.Cus_n           == eph2.Cus_n) && ...
        (eph1.Cuc_n           == eph2.Cuc_n) && ...
        (eph1.t_oc            == eph2.t_oc) && ...
        (eph1.a_f0n           == eph2.a_f0n) && ...
        (eph1.a_f1n           == eph2.a_f1n) && ...
        (eph1.a_f2n           == eph2.a_f2n) && ...
        (eph1.URA_NED0        == eph2.URA_NED0) && ...
        (eph1.URA_NED1        == eph2.URA_NED1) && ...
        (eph1.URA_NED2        == eph2.URA_NED2);
