function receiver = pointPos_new(receiver, pvtForecast_Succ)
% pvtForecast_Succ 是否有预测值
% 支持双频定位

%% Initialization
recvSYST = receiver.syst;
config = receiver.config;
channels = receiver.channels;
actvPvtChannels = receiver.actvPvtChannels;
satelliteTable = receiver.satelliteTable;
naviMsg = receiver.naviMsg;
recv_timer = receiver.timer;
pvtCalculator = receiver.pvtCalculator;
rawP.GPS = [];
rawP.BDS = [];
satClkCorr.BDS = [];
satClkCorr.GPS = zeros(2,32);
satPositions.BDS = [];
satPositions.GPS = zeros(6,32);
% EphAll.BDS = [];
% EphAll.GPS = [];
transmitTime.BDS = [];
transmitTime.GPS = [];
CN0.BDS = [];
CN0.GPS = [];
L2toL1_delay = zeros(1,32);  %本地L1码相位减去L2码相位可得码相位延时

% Active channel list
svnum.BDS = actvPvtChannels.actChnsNum_BDS;% this flag is to find whether avaliable satellite is above 4
svnum.GPS = actvPvtChannels.actChnsNum_GPS;
activeChannel.BDS = actvPvtChannels.BDS(1:2, 1:svnum.BDS);
activeChannel.GPS = actvPvtChannels.GPS(1:2, 1:svnum.GPS);% avaliable channels

%c = 2.99792458e8;

%% Start PVT
if (svnum.BDS + svnum.GPS) >= 1
    %---------- 计算GPS观测量 ----------
    if svnum.GPS >= 1
        % 接收机周内秒，一开始以通道平均时间加70ms来估计，定位成功后获得精确值
        rxTime_GPS = recv_timer.recvSOW_GPS; 
        % 以L1为码相位为基准的通道周内时间
        [transmitTime.GPS] = findTransTime_GPS(channels, activeChannel.GPS(1,:));                 
        % 计算L1单频伪距
        [rawP.GPS] = calculatePseudoranges(transmitTime.GPS, rxTime_GPS, activeChannel.GPS);
        % 获取通道载噪比
        [CN0.GPS] = GPS_getChnCN0(channels, activeChannel.GPS);
        
        if strcmp('GPS_L1CA',recvSYST) % 单频模式计算卫星轨道和钟差
            [satPositions.GPS, satClkCorr.GPS, ~] = GPS_calculateSatPosition(...
                transmitTime.GPS, naviMsg.GPS_L1CA.ephemeris, activeChannel.GPS(2,:));
        elseif strcmp('L1CA_L2C',recvSYST)  % 双频模式计算卫星轨道和钟差                   
            for i=1:length(activeChannel.GPS(2,:))
                prn = activeChannel.GPS(2,i);               
                [satPositions.GPS(:,prn), satClkCorr.GPS(:,prn)] = GPS_calculateSatPosition_2(...
                    transmitTime.GPS(prn), naviMsg.GPS_L1CA.ephemeris(prn), naviMsg.GPS_L2C.ephemeris(prn), channels(i).SYST);
                %双频模式获取码相位差值（m)
                if ( strcmp('GPS_L1CA_L2C', channels(i).SYST))
                    L2toL1_delay(prn) = GPS_L1L2_codPhsDiff( channels(i).CH_L1CA_L2C );
                end
            end
        end
        
    end
    %---------- Compute BDS observables ----------
    if svnum.BDS >= 1
        rxTime_BDS = recv_time.recvSOW_BDS;
        % Find trasmition time
        [transmitTime.BDS] = findTransTime_BD(channels, activeChannel.BDS(1,:));
        % Compute satellite position
        [satPositions.BDS, satClkCorr.BDS, ~] = BD_calculateSatPosition(transmitTime.BDS, naviMsg.BDS_B1I.ephemeris, activeChannel.BDS(2,:));
        % Get the receiver local time
        
        % Compute the Pseudo-range / receiver time
        [rawP.BDS] = calculatePseudoranges(transmitTime.BDS, rxTime_BDS, activeChannel.BDS);
        % Get the channels' CN0 info
        [CN0.BDS] = BD_getChnCN0(channels, activeChannel.BDS);
    end
    
    if strcmp(recvSYST,'BDS_B1I')
        switch config.recvConfig.positionType
            case 00 % least-square single point positioning
                [pvtCalculator, recv_timer, satelliteTable(1)] = ...
                    lsPVT_resiraim_BDS(satPositions.BDS, ...
                                rawP.BDS, ...
                                transmitTime.BDS, ...
                                satClkCorr.BDS, ...
                                CN0.BDS, ...
                                config, ...
                                activeChannel.BDS, ...
                                satelliteTable(1), ...
                                naviMsg.BDS_B1I.ephemeris, ...
                                recv_timer, ...
                                pvtCalculator, ...
                                pvtForecast_Succ);
            case 01 % kalman single point positioning
                [pvtCalculator, recv_timer, satelliteTable(1)] = ...
                    kalmanPVT_resiraim_BDS(satPositions.BDS, ...
                                rawP.BDS, ...
                                transmitTime.BDS, ...
                                satClkCorr.BDS, ...
                                CN0.BDS, ...
                                config, ...
                                activeChannel.BDS, ...
                                satelliteTable(1), ...
                                naviMsg.BDS_B1I.ephemeris, ...
                                recv_timer, ...
                                pvtCalculator, ...
                                pvtForecast_Succ);
            case 02 %  MM-estimator single point positioning
                error('MM-estimator does not support single BDS constellation mode!')
        end
        
    elseif strcmp(recvSYST,'GPS_L1CA') || ( strcmp(recvSYST,'L1CA_L2C'))
        switch config.recvConfig.positionType
            case 100 % least-square single point positioning
                [pvtCalculator, recv_timer, satelliteTable(2)] = ...
                    lsPVT_resiraim_GPS_new(satPositions.GPS, ...% matrix[6x32], each column for a sat [x;y;z;vx;vy;vz]
                               rawP.GPS, ...% vector[1x32], each for a sat pseudorange [meter]
                               transmitTime.GPS, ...% vector[1x32], each for a sat transmit time [sec]
                               satClkCorr.GPS, ...% matrix[2x32], each colum for a sat [clk_dt; clk_df]
                               CN0.GPS, ...
                               L2toL1_delay, ...
                               config, ...% receiver config struct
                               channels, ...% receiver channel list, [nx1:channel]
                               activeChannel.GPS, ...% matrix[2xNum], row1 for channel ID list; row2 for prn list; Num for number of active channels
                               satelliteTable(2), ...
                               naviMsg.GPS_L1CA.ephemeris, ...% ephemeris para struct for GPS, [1x32 struct]
                               naviMsg.GPS_L2C, ...  %CNAV navigation message
                               recv_timer, ...
                               pvtCalculator, ...
                               pvtForecast_Succ);
            case 101 % kalman single point positioning
                [pvtCalculator, recv_timer, satelliteTable(2)] = ...
                    kalmanPVT_resiraim_GPS(satPositions.GPS, ...% matrix[6x32], each column for a sat [x;y;z;vx;vy;vz]
                               rawP.GPS, ...% vector[1x32], each for a sat pseudorange [meter]
                               transmitTime.GPS, ...% vector[1x32], each for a sat transmit time [sec]
                               satClkCorr.GPS, ...% matrix[2x32], each colum for a sat [clk_dt; clk_df]
                               CN0.GPS, ...
                               config, ...% receiver config struct
                               channels, ...% receiver channel list, [nx1:channel]
                               activeChannel.GPS, ...% matrix[2xNum], row1 for channel ID list; row2 for prn list; Num for number of active channels
                               satelliteTable(2), ...
                               naviMsg.GPS_L1CA.ephemeris, ...% ephemeris para struct for GPS, [1x32 struct]
                               recv_timer, ...
                               pvtCalculator, ...
                               pvtForecast_Succ);
            case 102 %  MM-estimator single point positioning
                error('MM-estimator does not support single GPS constellation mode!')
        end

    elseif  strcmp(recvSYST,'B1I_L1CA')
        switch config.recvConfig.positionType
            case 00 % least-square single point positioning
                [pvtCalculator, recv_timer, satelliteTable(1), satelliteTable(2)] = ...
                    lsPVT_resiraim_JointBdsGps(satPositions.BDS, satPositions.GPS, ...% matrix[6x32], each column for a sat [x;y;z;vx;vy;vz];
                               rawP.BDS, rawP.GPS, ...
                               transmitTime.BDS, transmitTime.GPS, ...
                               satClkCorr.BDS, satClkCorr.GPS, ...
                               CN0.BDS, CN0.GPS, ...
                               config, ...
                               activeChannel.BDS, activeChannel.GPS, ...
                               satelliteTable(1), satelliteTable(2), ...
                               naviMsg.BDS_B1I.ephemeris, naviMsg.GPS_L1CA.ephemeris, ...
                               recv_timer, ...
                               pvtCalculator, ...
                               pvtForecast_Succ);
                    
            case 01 % kalman single point positioning
                [pvtCalculator, recv_timer, satelliteTable(1), satelliteTable(2)] = ...
                    kalmanPVT_resiraim_JointBdsGps(satPositions.BDS, satPositions.GPS, ...% matrix[6x32], each column for a sat [x;y;z;vx;vy;vz];
                               rawP.BDS, rawP.GPS, ...
                               transmitTime.BDS, transmitTime.GPS, ...
                               satClkCorr.BDS, satClkCorr.GPS, ...
                               CN0.BDS, CN0.GPS, ...
                               config, ...
                               activeChannel.BDS, activeChannel.GPS, ...
                               satelliteTable(1), satelliteTable(2), ...
                               naviMsg.BDS_B1I.ephemeris, naviMsg.GPS_L1CA.ephemeris, ...
                               recv_timer, ...
                               pvtCalculator, ...
                               pvtForecast_Succ);
            case 02 % MM-estimator single point positioning
                [pvtCalculator, recv_timer, satelliteTable(1), satelliteTable(2)] = ...
                    mmPVT_stdraim_JoinGpsBds_v1(satPositions.BDS, satPositions.GPS, ...
                               rawP.BDS, rawP.GPS, ...
                               transmitTime.BDS, transmitTime.GPS, ...
                               satClkCorr.BDS, satClkCorr.GPS, ...
                               CN0.BDS, CN0.GPS, ...
                               config, ...
                               activeChannel.BDS, activeChannel.GPS, ...
                               satelliteTable(1), satelliteTable(2), ...
                               naviMsg.BDS_B1I.ephemeris, naviMsg.GPS_L1CA.ephemeris, ...
                               recv_timer, ...
                               pvtCalculator, ...
                               pvtForecast_Succ);
        end
    end
    
    pvtCalculator.positionTime = [recv_timer.year, recv_timer.month, recv_timer.day, recv_timer.hour, recv_timer.min, recv_timer.sec];
    pvtCalculator.logOutput.rawP = rawP;
    pvtCalculator.logOutput.satClkErr = satClkCorr;
    pvtCalculator.logOutput.satPos = satPositions;
    pvtCalculator.logOutput.transmitTime = transmitTime;
    pvtCalculator.logOutput.logReady = 1;
end



receiver.timer = recv_timer;
receiver.pvtCalculator = pvtCalculator;
receiver.satelliteTable = satelliteTable;


